### ISSUE TITLE
Extension fails to save info under managed Google profile

### ISSUE THREAD

**Issue by sarahec** [hkgnp/chrome-extension-logseq-quickcapture#11]
I have two Google accounts: an old personal gmail and a new Google Workspace for my work. The extension saves content to Logseq when used from the standalone Gmail, but not from the Google Workspace account.

## Tests (so far)

1. When both Google profiles are open, the extension only works with the personal email.
2. When logged out from the personal profile (only corp open), the extension still fails.
3. Could it be Logseq pinning to a profile?
  *   When both Google profiles are open, Logseq will open links in the older one (first in the profile list).
  *   When logged out from the personal profile, Logseq will open links in the corp profile.
4. Do other extensions work? Yes: the [Zotero connector](https://github.com/zotero/zotero-connectors) works across both profiles.

I'm the admin on the work account, and there are no restrictions on apps or extensions.

**Comment by benjypng** [comment]
Thanks for raising this. Unfortunately, I don't think that this is an extension issue. The extension simply grabs items like page title, URL, etc. and passes it into the Logseq callback URL. It has no control nor visibility of which profile the extension is being used from.

**Comment by sarahec** [comment]
FYI, I just found the error in your code. I'll open a new issue once I have a PR ready.
