### ISSUE TITLE
Fails to save pages that have a `#` character in the page's title

### ISSUE THREAD

**Issue by tedyoung** [hkgnp/chrome-extension-logseq-quickcapture#12]
I'm not sure if this is a problem with the extension, or the API being used by the extension.

Steps to recreate:

1. Go to https://fsharpforfunandprofit.com/rop/
2. Click on Logseq Quick Capture

Expected:

Page to be entered into Logseq with the full title and URL linked:

`**12:16** [[quick capture]]:  [Railway Oriented Programming | F# for fun and profit](https://fsharpforfunandprofit.com/rop/)`

Actual:

`**12:16** [[quick capture]]:  Railway Oriented Programming | F`

text including and after the `#` is cut-off.

**Comment by benjypng** [comment]
I have included a fix in v0.2.3. It is currently pending the webstore review.

**Comment by tedyoung** [comment]
Thanks for the prompt fix!

**Comment by benjypng** [comment]
Fix should be in already. Let me know how it goes.

**Comment by tedyoung** [comment]
Update works great, thanks!
