### ISSUE TITLE
Version mismatch between manifest and published

### ISSUE THREAD

**Issue by sarahec** [hkgnp/chrome-extension-logseq-quickcapture#13]
The [chrome web store](https://chromewebstore.google.com/detail/logseq-quick-capture/hdpmdgiddmjppbeahnglgagndmahlanc?pli=1) shows version 0.2.3 while the manifest shows 0.2.2.

**Comment by sarahec** [comment]
Note: My PR fixes this also.

**Comment by benjypng** [comment]
Fixed in latest!
