### ISSUE TITLE
Unable to capture selected content to Logseq, only the title's link can be captured.

### ISSUE THREAD

**Issue by r33452000** [hkgnp/chrome-extension-logseq-quickcapture#16]
Select the text and click the Logseq button, as shown in the image below.
![image](https://github.com/hkgnp/chrome-extension-logseq-quickcapture/assets/69714117/95a8beee-f328-4261-b0da-ca338b5d0aca)

Logseq Quick Capture 0.2.4
Chrome is currently up to date.
Version 124.0.6367.61 (Official Build) (64-bit)

Is this normal?

**Comment by benjypng** [comment]
A fix is in place. Waiting to update to the Chrome Store.

**Comment by benjypng** [comment]
Fixed in the latest version.
