### ISSUE TITLE
URL-only captures include `null` before URL

### ISSUE THREAD

**Issue by sarahec** [hkgnp/chrome-extension-logseq-quickcapture#17]
Version 0.2.5

## To reproduce

1. Open a web page
2. Do not make a text selection
3. Click the capture extension
4. Observe the newly-added `null`.

```
**14:43** [[quick capture]]: null [Youtube Video RAG Search - crewAI](https://docs.crewai.com/tools/YoutubeVideoSearchTool/)
```
## Cause

If`result` is null, don't include it in the `content` URL parameter.

**Comment by sarahec** [comment]
Apologies for the multiple updates, I had to dig to find the breakage. I had tested with and without a text selection (which worked), but forgot to url encode the result. So ASCII content worked, but apparently non-ASCII didn't.

**Comment by benjypng** [comment]
Thanks for reporting this! 0.2.6 is pending publication in the chrome store.

**Comment by benjypng** [comment]
0.2.6 is published.
