### ISSUE TITLE
Problems with the new tab workflow

### ISSUE THREAD

**Issue by sarahec** [hkgnp/chrome-extension-logseq-quickcapture#18]
1. Links don't always save when you click the extension (then click the tab and click OK). Since `main` was declared `async`, you *must* call it with await: `await main()`
2. The tabbed workflow is awkward and not always easy to get to in time. Is there a special reason you switched to it? 

I think the tabbed workflow part should be reverted, but maybe there's a special reason for it?

**Comment by benjypng** [comment]
Fixed in `0.2.10` (pending extensions store review).
Think I was cleaning up some stuff and copied over the Firefox code by mistake.

**Comment by sarahec** [comment]
That's excellent news! Thank you.
