### ISSUE TITLE
Custom template for capture

### ISSUE THREAD

**Issue by douglascamata** [hkgnp/chrome-extension-logseq-quickcapture#3]
I would love to be able to customize the text that goes into Logseq when a quick capture happens so that it better suits the way I use Logseq.

To expand on this, I would like to be able to have different templates depending on the website I'm on. Examples:

- When I quick-capture a Youtube page I would like to add a `#[[Watch]]` reference.
- When I quick-capture an Amazon page I would like to add a `#[[Shopping]]` reference.

**Comment by benjypng** [comment]
This is controlled by Logseq actually; templates for quick capture are set up in Logseq.
