### ISSUE TITLE
Feature Request: add separate keyboard shortcut options for sending to today or cursor

### ISSUE THREAD

**Issue by ahpatel** [hkgnp/chrome-extension-logseq-quickcapture#5]
Sometimes, I want to push a link to the cursor location and sometimes I want to send to the end of today's journal page.  

I have the default set to Append Today and generally push with a keyboard shortcut (i.e., CMD+SHIFT+L). For times when I want to send the link to the cursor location instead, it would be awesome if I could use a secondary keyboard shortcut  (CTRL+SHIFT+L)

This would save a few edits/seconds when I'm in a page -- where, I currently have to flip from the page I'm on to the Journal, cut the link, go back to the page and paste it manually.

**Comment by benjypng** [comment]
This is actually controlled via the `config.edn` settings from within Logseq, and not in the extension itself. Look for the quick capture options within `config.edn`. I have extracted the excerpt for your reference:

```
 ;; Quick capture templates for receiving content from other apps.
 ;; Each template contains three elements {time}, {text} and {url}, which can be auto-expanded
 ;; by receiving content from other apps. Note: the {} cannot be omitted.
 ;; - {time}: capture time
 ;; - {date}: capture date using current date format, use `[[{date}]]` to get a page reference
 ;; - {text}: text that users selected before sharing.
 ;; - {url}: URL or assets path for media files stored in Logseq.
 ;; You can also reorder them or use only one or two of them in the template.
 ;; You can also insert or format any text in the template, as shown in the following examples.
 ;; :quick-capture-templates
 ;; {:text "[[quick capture]] **{time}**: {text} from {url}"
 ;;  :media "[[quick capture]] **{time}**: {url}"}
```
