### ISSUE TITLE
Formatting custom excerpt text

### ISSUE THREAD

**Issue by ghost** [hkgnp/chrome-extension-logseq-quickcapture#6]
I was very happy when I discovered the "Logseq Quick Capture" plugin, which can directly extract text from web pages.
 
Is it possible to remove the "time stamp" and the "[[quick capture]]:" mark to make the excerpt text more pure. Even, we can change the format we want . for example, adding quotation marks around the text, like this "This is an excerpt".
![Attachment-1](https://user-images.githubusercontent.com/122197875/211184459-32890a5f-4bb5-412c-8058-a41a646c849e.png)

**Comment by benjypng** [comment]
You can customise this in your `config.edn` file. Look for `quick-capture-templates` there and modify as necessary!
