### ISSUE TITLE
"cursor" plus "append"=true does not work.

### ISSUE THREAD

**Issue by svnk** [hkgnp/chrome-extension-logseq-quickcapture#7]
Chrome Version 110.0.5481.177 on MacOS 13.2.1 , plugin version 0.2.1

capture to TODAY works fine, as does capturing to a specific page.

capture to CURSOR flashes logsync and then does not enter text. 

Also tried to disable all other plugins to avoid problems caused by that.

**Comment by benjypng** [comment]
Did you set `append` to no?

**Comment by svnk** [comment]
![image](https://user-images.githubusercontent.com/2069523/221412517-7e9fbddb-e361-40d6-82ce-4749e91ac338.png)

Yes, but according to the description, that should not matter.

OK, after changing append to "no", it works. Logseq needs to be in edit mode (unsurprisingly).


So, changing bug to "cursor" plus "append"=true does not work.

**Comment by benjypng** [comment]
Fixed in latest version.
