### ISSUE TITLE
Adding Hashtags and/or square brackets

### ISSUE THREAD

**Issue by lmendez5** [hkgnp/chrome-extension-logseq-quickcapture#8]
Hi there... I like very much this extension, very useful. 
I was wondering if is it possible to let the hashtag (#) and/or the square brackets ([[]]) do their job in the selected text.
This is because I would like to add this to my gmail, for example,`Dear [[Mr Bruce Wang]] I have this [[LogSEQ Project]] and ...`  so, I send the email and before it get lost in my Sent Emails, well, I use your extension to add the selected text to logseq and `Mr Bruce Wang` and `LogSEQ Prject` will become a nodes. 
What do you think??

**Comment by benjypng** [comment]
Hi, unfortunately this is not possible without injecting something in between the selecting of text in the browser and inserting into Logseq. Apologies.
